name: Build & publish stable Node package

on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    name: Build & publish

    env:
      CI: true
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch
        run: |
          git fetch --prune --unshallow
          git fetch origin 'master:master'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
          yarn install --frozen-lockfile --production=false
      - name: Publish
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name ${GITHUB_ACTOR}
          yarn bumped release $(yarn --silent get-next-version)
          yarn config set //registry.yarnpkg.com/:_authToken=$NPM_AUTH_TOKEN
          yarn run publish:default
