name: Node CI

on:
  push:
    branches-ignore:
      - 'wip-**'
      - '**-wip'

jobs:
  build:
    name: Build, lint & test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, and test
        run: |
          yarn install --frozen-lockfile
          yarn run check-types
          yarn run lint
          yarn run build
          yarn test
        env:
          CI: true
